name: Generate Snake Animation

on:
  # Triggers the workflow diariamente
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Gera a animação da cobrinha
      - uses: Platane/snk@v2
        with:
          github_user_name: kaique321123
          outputs: dist/snake.svg

      # Salva a animação no branch "output"
      - name: Deploy animation
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
